apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "labels" .}}
spec:
  replicas: {{.Values.replicasCount}}
  selector:
    matchLabels:
      {{- include "labels" . | indent 2}}
  template:
    metadata:
      labels:
        {{- include "labels" . | indent 4}}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: hello-world
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
